name: lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2.4.1
      with:
        node-version: '15'
    - uses: actions/cache@v3.0.4
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
    - run: npm ci
    - run: npx openapi lint reference/*.yaml
